version: '3.0'
services:
  app:
    build: .
    image: starcraft-extension-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS=redis
      - MONGO_URL=mongodb://mongodb/starcraft-twitch-db
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"