version: '2.0'
services:
  base:
    build: .
    image: starcraft-extension
    ports:
      - "3000:3000"
    environment:
      CONFIG_ENGINE_NAME: "simple-local-fs"
  links:
    — mongo
  mongo:
    image: mongo
    ports:
    — “27017:27017”