version: '3.3'
services:
  app:
    build: .
    image: starcraft-extension-server
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS=redis
      - MONGO_URL=mongodb://mongodb/starcraft-twitch-db
  mongodb:
    image: andresvidal/rpi3-mongodb3:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"
