version: '3.3'
services:
  base:
    build: .
    image: starcraft-extension
    ports:
      - "3000:3000"
    environment:
      CONFIG_ENGINE_NAME: "simple-local-fs"
      MONGO_URL: "mongodb://admin:8IgDVV0eYLyclJ7N@mongodb.starcraft-server-extension.svc:27017/starcraft-twitch-db"